### ISSUE TITLE
1.16.1 Server Crash

### ISSUE THREAD

**Issue by Vanblam** [gbl/DurabilityViewer#31]
I have 51 mods installed so I'm assuming it might be a compatibility issue. here is the crash report.

[12Jul2020 17:32:38.299] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 32.0.63, --fml.mcpVersion, 20200625.160719, --fml.mcVersion, 1.16.1, --fml.forgeGroup, net.minecraftforge, nogui]
[12Jul2020 17:32:38.302] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 5.1.0+69+master.79f13f7 starting: java version 1.8.0_231 by Oracle Corporation
[12Jul2020 17:32:38.517] [main/INFO] [net.minecraftforge.fml.loading.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[12Jul2020 17:32:39.417] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlserver' with arguments [--gameDir, ., nogui]
[12Jul2020 17:32:49.323] [main/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `forbidden_arcanus` for name `edelwood_sign`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[12Jul2020 17:32:49.326] [main/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `forbidden_arcanus` for name `edelwood_wall_sign`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[12Jul2020 17:32:49.327] [main/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `forbidden_arcanus` for name `cherrywood_sign`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[12Jul2020 17:32:49.328] [main/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `forbidden_arcanus` for name `cherrywood_wall_sign`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[12Jul2020 17:32:49.329] [main/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `forbidden_arcanus` for name `mysterywood_sign`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[12Jul2020 17:32:49.329] [main/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `forbidden_arcanus` for name `mysterywood_wall_sign`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[12Jul2020 17:32:49.563] [modloading-worker-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `minecraft` for name `invisibility`, expected `potionsmaster`. This could be a intended override, but in most cases indicates a broken mod.
[12Jul2020 17:32:49.572] [modloading-worker-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `minecraft` for name `long_invisibility`, expected `potionsmaster`. This could be a intended override, but in most cases indicates a broken mod.
[12Jul2020 17:32:49.673] [modloading-worker-2/ERROR] [net.minecraft.util.Util/]: No data fixer registered for botany_pot
[12Jul2020 17:32:49.803] [modloading-worker-4/ERROR] [net.minecraft.util.Util/]: No data fixer registered for forbidden_arcanus:chorus_pearl
[12Jul2020 17:32:49.810] [modloading-worker-7/INFO] [mod.alexndr.simpleores.SimpleOres/]: Hello from Simple Ores!
[12Jul2020 17:32:49.828] [modloading-worker-3/INFO] [net.minecraftforge.common.ForgeMod/FORGEMOD]: Forge mod loading, version 32.0.63, for MC 1.16.1 with MCP 20200625.160719
[12Jul2020 17:32:49.829] [modloading-worker-3/INFO] [net.minecraftforge.common.MinecraftForge/FORGE]: MinecraftForge v32.0.63 Initialized
[12Jul2020 17:32:49.883] [modloading-worker-4/ERROR] [net.minecraft.util.Util/]: No data fixer registered for forbidden_arcanus:seed_bullet
[12Jul2020 17:32:50.259] [modloading-worker-4/ERROR] [net.minecraft.util.Util/]: No data fixer registered for forbidden_arcanus:energy_ball
[12Jul2020 17:32:50.266] [modloading-worker-4/ERROR] [net.minecraft.util.Util/]: No data fixer registered for forbidden_arcanus:boom_arrow
[12Jul2020 17:32:50.269] [modloading-worker-4/ERROR] [net.minecraft.util.Util/]: No data fixer registered for forbidden_arcanus:draco_arcanus_arrow
[12Jul2020 17:32:50.280] [modloading-worker-4/ERROR] [net.minecraft.util.Util/]: No data fixer registered for forbidden_arcanus:pixie
[12Jul2020 17:32:50.374] [modloading-worker-9/INFO] [ironfurnaces.IronFurnaces/]: Initializing Update Checker...
[12Jul2020 17:32:50.378] [ Iron Furnaces Update Checker/INFO] [ironfurnaces.IronFurnaces/]: Starting Update Check...
[12Jul2020 17:32:50.882] [ Iron Furnaces Update Checker/INFO] [ironfurnaces.IronFurnaces/]: Update Check done!
[12Jul2020 17:32:50.882] [ Iron Furnaces Update Checker/INFO] [ironfurnaces.IronFurnaces/]: Iron Furnaces is up to date!
[12Jul2020 17:32:50.961] [main/INFO] [net.minecraftforge.fml.DeferredWorkQueue/LOADING]: Dispatching synchronous work after CONSTRUCT: 2 jobs
[12Jul2020 17:32:50.981] [main/INFO] [net.minecraftforge.fml.DeferredWorkQueue/LOADING]: Synchronous work queue completed in 00:00:00.016
[12Jul2020 17:32:51.620] [main/INFO] [bno/]: Blocks Registered
[12Jul2020 17:32:51.635] [main/INFO] [bno/]: Ore Blocks Registered
[12Jul2020 17:32:51.651] [main/INFO] [Botany Pots/]: Registered 34 Block entries.
[12Jul2020 17:32:51.751] [main/INFO] [mcwdoors/]: Blocks registered.
[12Jul2020 17:32:51.774] [main/INFO] [mcwbridges/]: Blocks registered.
[12Jul2020 17:32:52.682] [main/INFO] [bno/]: ItemBlocks Registered
[12Jul2020 17:32:52.684] [main/INFO] [bno/]: Ingots Registered
[12Jul2020 17:32:52.738] [main/INFO] [Botany Pots/]: Registered 34 Item entries.
[12Jul2020 17:32:52.750] [main/INFO] [mcwdoors/]: Items registered.
[12Jul2020 17:32:52.775] [main/INFO] [mcwbridges/]: Items registered.
[12Jul2020 17:32:52.853] [main/INFO] [Bookshelf/]: Registered 11 GlobalLootModifierSerializer entries.
[12Jul2020 17:32:53.197] [main/INFO] [Botany Pots/]: Registered 1 TileEntityType entries.
[12Jul2020 17:32:53.289] [main/ERROR] [net.minecraft.util.Util/]: No data fixer registered for cannon_skull
[12Jul2020 17:32:53.300] [main/ERROR] [net.minecraft.util.Util/]: No data fixer registered for guardvillagers:guard
[12Jul2020 17:32:53.346] [main/ERROR] [net.minecraft.util.Util/]: No data fixer registered for gravestone:player_ghost
[12Jul2020 17:32:53.582] [main/INFO] [Botany Pots/]: Registered 3 IRecipeSerializer entries.
[12Jul2020 17:32:53.662] [main/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `minecraft` for name `mineshaft`, expected `bettermineshafts`. This could be a intended override, but in most cases indicates a broken mod.
[12Jul2020 17:32:53.712] [modloading-worker-2/INFO] [ring_of_attraction/]: RingOfAttraction common setup
[12Jul2020 17:32:53.712] [modloading-worker-15/INFO] [mcwbridges/]: Setup method registered
[12Jul2020 17:32:53.714] [modloading-worker-11/WARN] [supertools/]: FMLCommonSetupEvent
[12Jul2020 17:32:53.725] [modloading-worker-11/WARN] [net.minecraftforge.common.BiomeDictionary/]: No types have been added to Biome minecraft:bamboo_jungle, types have been assigned on a best-effort guess: [JUNGLE, WET, HOT]
[12Jul2020 17:32:53.727] [modloading-worker-7/WARN] [net.minecraftforge.common.BiomeDictionary/]: No types have been added to Biome minecraft:bamboo_jungle_hills, types have been assigned on a best-effort guess: [JUNGLE, WET, HOT]
[12Jul2020 17:32:53.730] [modloading-worker-7/WARN] [net.minecraftforge.common.BiomeDictionary/]: No types have been added to Biome minecraft:crimson_forest, types have been assigned on a best-effort guess: [DRY, HOT, NETHER]
[12Jul2020 17:32:53.727] [modloading-worker-11/WARN] [net.minecraftforge.common.BiomeDictionary/]: No types have been added to Biome minecraft:soul_sand_valley, types have been assigned on a best-effort guess: [DRY, HOT, NETHER]
[12Jul2020 17:32:53.731] [modloading-worker-7/WARN] [net.minecraftforge.common.BiomeDictionary/]: No types have been added to Biome minecraft:warped_forest, types have been assigned on a best-effort guess: [DRY, HOT, NETHER]
[12Jul2020 17:32:53.732] [modloading-worker-15/FATAL] [net.minecraftforge.fml.loading.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/settings/KeyBinding for invalid dist DEDICATED_SERVER
[12Jul2020 17:32:53.731] [modloading-worker-11/WARN] [net.minecraftforge.common.BiomeDictionary/]: No types have been added to Biome minecraft:basalt_deltas, types have been assigned on a best-effort guess: [DRY, HOT, NETHER]
[12Jul2020 17:32:53.735] [modloading-worker-12/INFO] [mcwdoors/]: Setup method registered
[12Jul2020 17:32:53.737] [modloading-worker-11/INFO] [bno/]: Setup Method Registered (PreInit)
[12Jul2020 17:32:53.738] [modloading-worker-8/INFO] [Bookshelf/]: Registering 2 command argument types.
[12Jul2020 17:32:53.739] [modloading-worker-15/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/]: Exception caught during firing event: Attempted to load class net/minecraft/client/settings/KeyBinding for invalid dist DEDICATED_SERVER
	Index: 1
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$2593/727344543@5ca93ee9
java.lang.RuntimeException: Attempted to load class net/minecraft/client/settings/KeyBinding for invalid dist DEDICATED_SERVER
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClass(RuntimeDistCleaner.java:71)
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClass(ILaunchPluginService.java:103)
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:115)
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:239)
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:126)
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:96)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at de.guntram.mcmod.durabilityviewer.handler.KeyHandler.init(KeyHandler.java:11)
	at de.guntram.mcmod.durabilityviewer.DurabilityViewer.init(DurabilityViewer.java:41)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:106)
	at java.util.function.Consumer.lambda$andThen$0(Unknown Source)
	at java.util.function.Consumer.lambda$andThen$0(Unknown Source)
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112)
	at net.minecraftforge.fml.ModList.lambda$null$10(ModList.java:135)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
	at java.util.concurrent.CountedCompleter.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

[12Jul2020 17:32:53.746] [modloading-worker-15/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Caught exception during event FMLCommonSetupEvent dispatch for modid durabilityviewer
java.lang.RuntimeException: Attempted to load class net/minecraft/client/settings/KeyBinding for invalid dist DEDICATED_SERVER
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClass(RuntimeDistCleaner.java:71) ~[forge-1.16.1-32.0.63.jar:32.0]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClass(ILaunchPluginService.java:103) ~[modlauncher-5.1.0.jar:5.1.0+69+master.79f13f7]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:115) ~[modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:239) ~[modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:126) ~[modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:96) ~[modlauncher-5.1.0.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_231]
	at de.guntram.mcmod.durabilityviewer.handler.KeyHandler.init(KeyHandler.java:11) ~[?:1.16.1-forge32.0.38-1.7.1]
	at de.guntram.mcmod.durabilityviewer.DurabilityViewer.init(DurabilityViewer.java:41) ~[?:1.16.1-forge32.0.38-1.7.1]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-2.2.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-2.2.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:106) ~[?:32.0]
	at java.util.function.Consumer.lambda$andThen$0(Unknown Source) ~[?:1.8.0_231]
	at java.util.function.Consumer.lambda$andThen$0(Unknown Source) ~[?:1.8.0_231]
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112) ~[?:?]
	at net.minecraftforge.fml.ModList.lambda$null$10(ModList.java:135) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) [?:1.8.0_231]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) [?:1.8.0_231]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) [?:1.8.0_231]
	at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) [?:1.8.0_231]
	at java.util.concurrent.CountedCompleter.exec(Unknown Source) [?:1.8.0_231]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_231]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_231]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_231]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_231]
[12Jul2020 17:32:53.753] [modloading-worker-11/INFO] [doubleslabs/]: Successfully added slab support for type MinecraftSlabSupport
[12Jul2020 17:32:53.905] [modloading-worker-14/INFO] [com.jaquadro.minecraft.storagedrawers.StorageDrawers/]: New compacting rule 4 clay_ball = 1 clay
[12Jul2020 17:32:53.906] [modloading-worker-14/INFO] [com.jaquadro.minecraft.storagedrawers.StorageDrawers/]: New compacting rule 4 snowball = 1 snow_block
[12Jul2020 17:32:53.907] [modloading-worker-1/WARN] [net.minecraft.network.datasync.EntityDataManager/]: defineId called for: class net.minecraft.entity.passive.ParrotEntity from class com.stal111.forbidden_arcanus.entity.PixieEntity
[12Jul2020 17:32:53.908] [modloading-worker-14/INFO] [com.jaquadro.minecraft.storagedrawers.StorageDrawers/]: New compacting rule 4 glowstone_dust = 1 glowstone
[12Jul2020 17:32:53.910] [modloading-worker-14/INFO] [com.jaquadro.minecraft.storagedrawers.StorageDrawers/]: New compacting rule 4 brick = 1 bricks
[12Jul2020 17:32:53.911] [modloading-worker-14/INFO] [com.jaquadro.minecraft.storagedrawers.StorageDrawers/]: New compacting rule 4 nether_brick = 1 nether_bricks
[12Jul2020 17:32:53.912] [modloading-worker-14/INFO] [com.jaquadro.minecraft.storagedrawers.StorageDrawers/]: New compacting rule 9 nether_wart = 1 nether_wart_block
[12Jul2020 17:32:53.913] [modloading-worker-14/INFO] [com.jaquadro.minecraft.storagedrawers.StorageDrawers/]: New compacting rule 4 quartz = 1 quartz_block
[12Jul2020 17:32:53.914] [modloading-worker-14/INFO] [com.jaquadro.minecraft.storagedrawers.StorageDrawers/]: New compacting rule 9 melon_slice = 1 melon
[12Jul2020 17:32:53.915] [modloading-worker-14/INFO] [com.jaquadro.minecraft.storagedrawers.StorageDrawers/]: New compacting rule 4 sand = 1 sandstone
[12Jul2020 17:32:53.920] [modloading-worker-14/INFO] [com.jaquadro.minecraft.storagedrawers.StorageDrawers/]: New compacting rule 4 red_sand = 1 red_sandstone
[12Jul2020 17:32:53.921] [modloading-worker-14/INFO] [com.jaquadro.minecraft.storagedrawers.StorageDrawers/]: New compacting rule 4 clay_ball = 1 clay
[12Jul2020 17:32:53.967] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [ma-enchants] Starting version check at https://raw.githubusercontent.com/Maciej916/Ma-Enchants/1.16/update.json
[12Jul2020 17:32:54.182] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [ma-enchants] Found status: UP_TO_DATE Current: 1.16.1-3.2.1 Target: null
[12Jul2020 17:32:54.184] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [falling_tree] Starting version check at https://raw.githubusercontent.com/RakSrinaNa/FallingTree/1.15.2/update.json
[12Jul2020 17:32:54.200] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [falling_tree] Found status: BETA Current: 2.1.5 Target: null
[12Jul2020 17:32:54.200] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [reap] Starting version check at http://maxhenkel.de/update/reap.json
[12Jul2020 17:32:54.916] [modloading-worker-0/INFO] [CraftTweaker/]: CraftTweaker has loaded successfully!
[12Jul2020 17:32:54.917] [main/INFO] [net.minecraftforge.fml.DeferredWorkQueue/LOADING]: Dispatching synchronous work after COMMON_SETUP: 5 jobs
[12Jul2020 17:32:55.031] [main/INFO] [net.minecraftforge.fml.DeferredWorkQueue/LOADING]: Synchronous work queue completed in 00:00:00.112
[12Jul2020 17:32:55.031] [main/FATAL] [net.minecraftforge.fml.ModLoader/LOADING]: Failed to complete lifecycle event SETUP, 1 errors found
[12Jul2020 17:32:55.033] [main/FATAL] [net.minecraft.server.Main/]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	Giselbaers Durability Viewer (durabilityviewer) encountered an error during the common_setup event phase
§7Attempted to load class net/minecraft/client/settings/KeyBinding for invalid dist DEDICATED_SERVER
]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:218) ~[?:?]
	at net.minecraftforge.fml.ModLoader.loadMods(ModLoader.java:156) ~[?:?]
	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:50) ~[?:?]
	at net.minecraft.server.Main.main(Main.java:94) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_231]
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.1-32.0.63.jar:32.0]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?]
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.1-32.0.63.jar:?]
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.1-32.0.63.jar:?]
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.1-32.0.63.jar:?]

**Comment by gbl** [comment]
Seems like you're loading the mod on a dedicated server. Durability Viewer is purely client side, it doesn't need a server part. Just omit it.

**Comment by Vanblam** [comment]
I just realized that this morning and did a facepalm LOL
