### ISSUE TITLE
Crash with Minecraft 1.14.2

### ISSUE THREAD

**Issue by Nova900** [gbl/DurabilityViewer#4]
The game crashes directly on start with this mod installed. I use Minecraft 1.14.2 with Fabric 0.4.2.27.
Here the error log:

[main/INFO]: Loading for game Minecraft 1.14.2
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: Failed to resolve mods!
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:147)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:120)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	... 8 more
Caused by: net.fabricmc.loader.discovery.ModResolutionException: Could not resolve valid mod collection (at: durabilityviewer requires {fabric @ [*]})
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:185)
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:483)
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:145)
	... 10 more
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117)
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97)
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81)
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401)
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:183)
	... 12 more

**Comment by Nova900** [comment]
Well, after installing the Fabric API it works. Sorry for wasting your time just because I didn't see that I had to install an additional mod after installing Fabric...
Suggestion: Add a note that the mods need the Fabric API. Just to help other stupid people like me. ^^
