### ISSUE TITLE
Fails to load - Fabric not found

### ISSUE THREAD

**Issue by monsterrideop** [gbl/DurabilityViewer#43]
First the version info. I'm using MultiMC to launch the game and keep track of the mods.
Minecraft 1.16.3
Fabric 0.10.1+build.209

Before adding the mod I have verified that the game and fabric both work.
After adding the mod I get the following errors in the log and the game fails to load.
```
[16:47:29] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: durabilityviewer requires {fabric @ [*]}
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:169) ~[fabric-loader-0.10.1+build.209.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:605) ~[fabric-loader-0.10.1+build.209.jar:?]
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:206) ~[fabric-loader-0.10.1+build.209.jar:?]
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:196) [fabric-loader-0.10.1+build.209.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:127) [fabric-loader-0.10.1+build.209.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.10.1+build.209.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:167) ~[fabric-loader-0.10.1+build.209.jar:?]
	... 13 more
```

**Comment by gbl** [comment]
This looks like you installed the fabric loader, but not the api (which is exactly what happens when you use the "install Fabric" button in MultiMC). You'll also need this:
https://www.curseforge.com/minecraft/mc-mods/fabric-api
