### ISSUE TITLE
Tried to load the mod and it crashed upon opening (I've tried fabric loader 0.12.6 & 0.12.8 but to no avail)

### ISSUE THREAD

**Issue by Megalonumber0ne** [gbl/DurabilityViewer#64]
net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric, any version.
Unmet dependency listing:
	 - Mod 'Giselbaers Durability Viewer' (durabilityviewer) 1.18-fabric0.43.1-1.10.2 requires any version of fabric, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:188)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric, any version.
Unmet dependency listing:
	 - Mod 'Giselbaers Durability Viewer' (durabilityviewer) 1.18-fabric0.43.1-1.10.2 requires any version of fabric, which is missing!
	at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:183)
	at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:48)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:222)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:186)
![image](https://user-images.githubusercontent.com/87905744/144707396-99247ef9-96c1-4744-a09b-ee18018bdee4.png)

**Comment by Megalonumber0ne** [comment]
![image](https://user-images.githubusercontent.com/87905744/144707434-6ecf7ddd-a257-44a3-b205-1e34f4e8a847.png)
This is proof I am using fabric loader

**Comment by gbl** [comment]
You have the loader, but you also need the api, from 
https://modrinth.com/mod/fabric-api/version/RSZHmY2f
or
https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/3546679
