### ISSUE TITLE
[1.20.1] Game crashed

### ISSUE THREAD

**Issue by eVic75** [gbl/DurabilityViewer#86]
Hi.
I love your mods, I use 6 of them, thank you for update to 1.20.1, but...

MC version 1.20.1
fabric-api-0.84.0+1.20.1
Fabric Loader 0.14.21
durabilityviewer-1.20-fabric0.83.0-1.10.3

Game crashed:
```
`The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'durabilityviewer'!`

```
```
`java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'durabilityviewer'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:458)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassCastException: class de.guntram.mcmod.fabrictools.Types.ConfigurationMinecraftColor cannot be cast to class java.lang.Integer (de.guntram.mcmod.fabrictools.Types.ConfigurationMinecraftColor is in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @57175e74; java.lang.Integer is in module java.base of loader 'bootstrap')
	at de.guntram.mcmod.fabrictools.Configuration.getIndexedColor(Configuration.java:115)
	at de.guntram.mcmod.durabilityviewer.handler.ConfigurationHandler.loadConfig(ConfigurationHandler.java:97)
	at de.guntram.mcmod.durabilityviewer.handler.ConfigurationHandler.load(ConfigurationHandler.java:49)
	at de.guntram.mcmod.durabilityviewer.DurabilityViewer.onInitializeClient(DurabilityViewer.java:30)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 7 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:458)`
```

**Comment by gbl** [comment]
Thanks for the report, seems like I messed up something with the config library and most of the mods I uploaded today have an older buggy version. Going to be a long night recompiling and reuploading everything ...

**Comment by eVic75** [comment]
I use:
AdvancementInfo
EasierVillagerTrading
Beenfo
EasierCrafting
InfiniteVillagerTrading
FlightHelper

These mods work fine in their newest versions.

**Comment by gbl** [comment]
Could you do me a favor and drop the jar file from https://github.com/gbl/GBfabrictools/releases/tag/1.4 into your mods folder, and check if that fixes the problem?

(The problem is in the color selection code, which DurabilityViewer has to select the tooltip color, but the others don't).

**Comment by eVic75** [comment]
With GBfabrictools-1.4+1.20 everything works fine.
You're great :)

**Comment by gbl** [comment]
Great to hear, thanks. The next version of DurabilityViewer will include that one :)

**Comment by eVic75** [comment]
Version 1.10.4. works great, thank you.
And thank you for upfating EasierVillagerTrading and EasierCrafting. I can't live without these mods :)

Greetngs

**Comment by gbl** [comment]
In that case you might like https://modrinth.com/mod/easierchests as well, I can't live without the chest sorting ability :)

**Comment by eVic75** [comment]
Thanks, I know this mod. But I prefer manual sorting ;)
