### ISSUE TITLE
[Bug] Crash when tryng to enter a world [Solved] Conflict with trinkets mod

### ISSUE THREAD

**Issue by gmansoibd** [gbl/DurabilityViewer#89]
Instaled durabilityviewer-1.20-fabric0.83.0-1.10.4
Minecraft opens correctly but ones i try to enter any word, i get the folowwing error:
java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because "equipped" is null

The error report:
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because "equipped" is null
	at de.guntram.mcmod.durabilityviewer.client.gui.GuiItemDurability.onRenderGameOverlayPost(GuiItemDurability.java:178)
	at net.minecraft.class_329.handler$zod000$durabilityviewer$beforeRenderDebugScreen(class_329.java:2385)
	at net.minecraft.class_329.method_1753(class_329.java:260)
	at net.minecraft.class_757.method_3192(class_757.java:926)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at de.guntram.mcmod.durabilityviewer.client.gui.GuiItemDurability.onRenderGameOverlayPost(GuiItemDurability.java:178)
	at net.minecraft.class_329.handler$zod000$durabilityviewer$beforeRenderDebugScreen(class_329.java:2385)
	at net.minecraft.class_329.method_1753(class_329.java:260)
-- Affected level --
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:826)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by gbl** [comment]
It seems like you have Trinkets installed as well, and there's a problem with DurabilityViewer and Trinkets interacting. Please send the start of the log that has the list of the installed mods, so I can see which version of trinkets and which trinkets-adding mods you have.

**Comment by gmansoibd** [comment]
Here is the full crash log
[crash-2023-06-29_08.02.17-client.txt](https://github.com/gbl/DurabilityViewer/files/11902460/crash-2023-06-29_08.02.17-client.txt)

Can confirm that there is some kind of conflict with Trinkets / charmofundying.  After removing those 2 game will enter normaly

**Comment by gbl** [comment]
Could you please reenable Trinkets and charmofunding, replace durabilityviewer from this zip file (you need to unzip it as I can't put jars in comments directly), and check if it works?
[trinketfix.zip](https://github.com/gbl/DurabilityViewer/files/11902645/trinketfix.zip)

**Comment by gmansoibd** [comment]
Spot on!
With that version you gave me i can now enter into worlds. 
Ty very much!

**Comment by gbl** [comment]
Thanks for the info. I hope the rest (DurabilityViewer shows trinket durability) works as well. Will publish that version shortly.
